# --- CENTRALV specific parameters ---
# Independent PPO with value norm, layer_norm, orthogonal, value clip
# but, without death agent mask, data chunk

action_selector: "multinomial"
epsilon_start: .0
epsilon_finish: .0
epsilon_anneal_time: 10000
mask_before_softmax: True
mixer: "ippo"

runner: "parallel_goals"

buffer_size: 64
batch_size_run: 8
batch_size: 64
accumulated_episodes: 8

mac: 'gcmarl_mac'
agent: 'n_rnn'
t_max: 10050000

obs_agent_id: True

lr: 0.0002
critic_coef: 0.5
entropy: 0.001
gae_lambda: 0.95
mini_epochs: 8
eps_clip: 0.2
save_probs: True

agent_output_type: "pi_logits"
learner: "ppo_goal_learner"

use_layer_norm: True
use_orthogonal: True
gain: 0.01
use_value_norm: True

name: "ippo_env=8_adam_gae"

predefine: False
threshold_phi: 0.3
N_trans_effect: 10000
scaler: 100.00
max_window: 1
goal_buffer_size: 100
goal_shape: 16
fac_ciec: 0.00
fac_hanming: 10.00
fac_mdpr: 10.00

exp_alg: "count"
discrete_scale_count: 100
arrival_ratio: 0.5

